CREATE TABLE usuario
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(60)                             NOT NULL,
    password      VARCHAR(60)                             NOT NULL,
    enabled       BOOLEAN                                 NOT NULL,
    registration_date                                     DATE,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE usuario_roles
(
    usuario_id BIGINT NOT NULL,
    roles      VARCHAR(255)
);

ALTER TABLE usuario_roles ADD CONSTRAINT fk_usuario_roles_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id);