CREATE TABLE usuario
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(60)                             NULL,
    username      VARCHAR(60)                             NOT NULL,
    password      VARCHAR(60)                             NOT NULL,
    enabled       BOOLEAN                                 NOT NULL,
    registration_date                                     DATE,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE usuario_roles
(
    usuario_id BIGINT NOT NULL,
    roles      VARCHAR(255)
);

ALTER TABLE usuario_roles ADD CONSTRAINT fk_usuario_roles_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id);

-- USUARIO TESTE
INSERT INTO usuario (id, registration_date, email, enabled, password, username)
VALUES (1, '2023-12-18', 'matheusdalvino50@gmail.com', true, 'matheus123', 'Matheus Dalvino');

INSERT INTO usuario_roles (usuario_id, roles)
    VALUES (1, 'ROLE_ADMIN');

INSERT INTO usuario_roles (usuario_id, roles)
    VALUES (1, 'ROLE_USER');